Reduce gpg to one stage

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -156,20 +156,20 @@ stages:
         - pip install opencv-python-headless
 
     script: 
+        - echo "skipping tests for now"
         # FIXME: we should start from a docker iamge that already has LibGL setup
         - apt update && apt install libgl1-mesa-glx -y && rm -rf /var/lib/apt/lists/*  
         - ls wheelhouse
-        - ls dist
         - MB_PYTHON_TAG=$(echo ${CI_JOB_NAME} | sed 's/.*\/\(.*\)-manylinux2010/\1/')
         - VERSION=$(python -c "import setup; print(setup.VERSION)")
         - BDIST_WHEEL_PATH=wheelhouse/kwimage-${VERSION}-${MB_PYTHON_TAG}-*manylinux*_x86_64.whl
         - pip install $BDIST_WHEEL_PATH
         - pip install pygments
-        # - xdoctest -m kwimage --style=google all
         # - xdoctest kwimage --style=google all --mask 
         # Hack to test the installed wheel. TODO: make run_tests work better in this case.
         - mkdir -p foo && cd foo && pytest --cov-config ../.coveragerc --cov-report html --cov-report term --cov=kwimage --xdoc $(python -c "import ubelt; print(ubelt.modname_to_modpath('kwimage'))") ../tests
         - ls wheelhouse
+        - ls dist
           
     # Coverage is a regex that will parse the coverage from the test stdout
     coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
@@ -197,6 +197,7 @@ stages:
 
     script: 
         - echo "skipping tests for now"
+        # FIXME: we should start from a docker iamge that already has LibGL setup
         - apt update && apt install libgl1-mesa-glx -y && rm -rf /var/lib/apt/lists/*  
         - ls wheelhouse
         - MB_PYTHON_TAG=py3-none-any
@@ -209,24 +210,29 @@ stages:
         - export KWIMAGE_DISABLE_C_EXTENSIONS=1
         - pip install -r requirements/tests.txt
         - mkdir -p foo && cd foo && python -m pytest --cov-config ../.coveragerc --cov-report html --cov-report term --cov=kwimage --xdoc $(python -c "import ubelt; print(ubelt.modname_to_modpath('kwimage'))") ../tests
+        - ls wheelhouse
+        - ls dist
           
     # Coverage is a regex that will parse the coverage from the test stdout
     coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
 
 
-.gpgsign_template: &gpgsign_template
+gpgsign/wheels:
     <<: 
         - *common_template
+
+    image:
+        python:3.8
 
     stage: 
         gpgsign
 
     script: 
         - ls wheelhouse
-        - MB_PYTHON_TAG=$(echo ${CI_JOB_NAME} | sed 's/.*\/\(.*\)-manylinux2010/\1/')
-        - VERSION=$(python -c "import setup; print(setup.VERSION)")
-        - BDIST_WHEEL_PATH=wheelhouse/kwimage-${VERSION}-${MB_PYTHON_TAG}-*manylinux*_x86_64.whl
-        - echo "BDIST_WHEEL_PATH = ${BDIST_WHEEL_PATH}"
+        - ls dist
+        #- MB_PYTHON_TAG=$(echo ${CI_JOB_NAME} | sed 's/.*\/\(.*\)-manylinux2010/\1/')
+        #- VERSION=$(python -c "import setup; print(setup.VERSION)")
+        #- BDIST_WHEEL_PATH=wheelhouse/kwimage-${VERSION}-${MB_PYTHON_TAG}-*manylinux*_x86_64.whl
         # Decrypt and import GPG Keys / trust
         - export GPG_EXECUTABLE=gpg
         - export GPG_KEYID=D297D757
@@ -238,17 +244,31 @@ stages:
         - GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/gpg_owner_trust.enc | $GPG_EXECUTABLE --import-ownertrust
         - GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/ci_secret_gpg_key.pgp.enc | $GPG_EXECUTABLE --import 
         - GPG_SIGN_CMD="$GPG_EXECUTABLE --batch --yes --detach-sign --armor --local-user $GPG_KEYID"
-        #- # $GPG_EXECUTABLE --list-keys
-        - echo "Signing wheels"
-        # -$GPG_SIGN_CMD --output $BDIST_WHEEL_PATH.asc $BDIST_WHEEL_PATH
-        - $GPG_SIGN_CMD $BDIST_WHEEL_PATH
-        - ls wheelhouse
-        - echo "Verifying wheels"
-        - $GPG_EXECUTABLE --verify $BDIST_WHEEL_PATH.asc $BDIST_WHEEL_PATH  || echo "hack, the first run of gpg very fails"
-        - $GPG_EXECUTABLE --verify $BDIST_WHEEL_PATH.asc $BDIST_WHEEL_PATH 
-        - echo "Verified wheels"
+
+        - |
+            WHEEL_PATHS=(wheelhouse/*.whl)
+            WHEEL_PATHS_STR=$(printf '"%s" ' "${WHEEL_PATHS[@]}")
+            echo "$WHEEL_PATHS_STR"
+            for WHEEL_PATH in "${WHEEL_PATHS[@]}"
+            do
+                echo "------"
+                echo "WHEEL_PATH = $WHEEL_PATH"
+                $GPG_SIGN_CMD --output $WHEEL_PATH.asc $WHEEL_PATH
+                $GPG_EXECUTABLE --verify $WHEEL_PATH.asc $WHEEL_PATH  || echo "hack, the first run of gpg very fails"
+                $GPG_EXECUTABLE --verify $WHEEL_PATH.asc $WHEEL_PATH 
+                twine check $WHEEL_PATH.asc $WHEEL_PATH
+            done
         - ls wheelhouse
         - ls dist
+
+        #- # $GPG_EXECUTABLE --list-keys
+        #- echo "Signing wheels"
+        #- $GPG_SIGN_CMD --output $BDIST_WHEEL_PATH.asc $BDIST_WHEEL_PATH
+        #- ls wheelhouse
+        #- echo "Verifying wheels"
+        #- $GPG_EXECUTABLE --verify $BDIST_WHEEL_PATH.asc $BDIST_WHEEL_PATH  || echo "hack, the first run of gpg very fails"
+        #- $GPG_EXECUTABLE --verify $BDIST_WHEEL_PATH.asc $BDIST_WHEEL_PATH 
+        #- echo "Verified wheels"
 
     artifacts:
         paths:
@@ -263,9 +283,12 @@ stages:
             - release
 
 
-.deploy_template: &deploy_template
+deploy/wheels:
     <<: 
         - *common_template
+
+    image:
+        python:3.8
 
     stage: 
         deploy
@@ -274,16 +297,25 @@ stages:
         - pip install six pyopenssl ndg-httpsclient pyasn1 requests[security] twine -U 
         - ls wheelhouse
         - ls dist
-        - MB_PYTHON_TAG=$(echo ${CI_JOB_NAME} | sed 's/.*\/\(.*\)-manylinux2010/\1/')
-        - VERSION=$(python -c "import setup; print(setup.VERSION)")
-        - BDIST_WHEEL_PATH=wheelhouse/kwimage-${VERSION}-${MB_PYTHON_TAG}-*manylinux*_x86_64.whl
-        - echo "Checking wheels MB_PYTHON_TAG $MB_PYTHON_TAG VERSION $VERSION BDIST_WHEEL_PATH $BDIST_WHEEL_PATH"
-        - ls -al ${BDIST_WHEEL_PATH}*
-        - twine check $BDIST_WHEEL_PATH.asc $BDIST_WHEEL_PATH
-        - echo "Uploading wheels"
+        #- MB_PYTHON_TAG=$(echo ${CI_JOB_NAME} | sed 's/.*\/\(.*\)-manylinux2010/\1/')
+        #- VERSION=$(python -c "import setup; print(setup.VERSION)")
+        #- BDIST_WHEEL_PATH=wheelhouse/kwimage-${VERSION}-${MB_PYTHON_TAG}-*manylinux2010_x86_64.whl
+        #- echo "Checking wheels MB_PYTHON_TAG $MB_PYTHON_TAG VERSION $VERSION BDIST_WHEEL_PATH $BDIST_WHEEL_PATH"
+        #- ls -al ${BDIST_WHEEL_PATH}*
+        #- twine check $BDIST_WHEEL_PATH.asc $BDIST_WHEEL_PATH
+        #- echo "Uploading wheels"
         # todo, can we tag the branch here as well?
         # note TWINE_USERNAME and TWINE_PASSWORD are protected variables only available on master and release branch
-        - twine upload --username $TWINE_USERNAME --password $TWINE_PASSWORD $BDIST_WHEEL_PATH.asc $BDIST_WHEEL_PATH
+        #- twine upload --username $TWINE_USERNAME --password $TWINE_PASSWORD $BDIST_WHEEL_PATH.asc $BDIST_WHEEL_PATH
+        - |
+            WHEEL_PATHS=(wheelhouse/*.whl)
+            WHEEL_PATHS_STR=$(printf '"%s" ' "${WHEEL_PATHS[@]}")
+            echo "$WHEEL_PATHS_STR"
+            for WHEEL_PATH in "${WHEEL_PATHS[@]}"
+            do
+                twine check $WHEEL_PATH.asc $WHEEL_PATH
+                twine upload --username $TWINE_USERNAME --password $TWINE_PASSWORD $WHEEL_PATH.asc $WHEEL_PATH
+            done
             
     only:
         refs:
@@ -313,17 +345,17 @@ test_minimal/cp39-cp39-manylinux2010:
     image:
         python:3.9
 
-gpgsign/cp39-cp39-manylinux2010:
-    <<: 
-        - *gpgsign_template
-    image:
-        python:3.9
+#gpgsign/cp39-cp39-manylinux2010:
+#    <<: 
+#        - *gpgsign_template
+#    image:
+#        python:3.9
 
-deploy/cp39-cp39-manylinux2010:
-    <<: 
-        - *deploy_template
-    image:
-        python:3.9
+#deploy/cp39-cp39-manylinux2010:
+#    <<: 
+#        - *deploy_template
+#    image:
+#        python:3.9
 
 # ---------------
 # Python 3.8 Jobs
@@ -346,17 +378,17 @@ test_minimal/cp38-cp38-manylinux2010:
     image:
         python:3.8
 
-gpgsign/cp38-cp38-manylinux2010:
-    <<: 
-        - *gpgsign_template
-    image:
-        python:3.8
+#gpgsign/cp38-cp38-manylinux2010:
+#    <<: 
+#        - *gpgsign_template
+#    image:
+#        python:3.8
 
-deploy/cp38-cp38-manylinux2010:
-    <<: 
-        - *deploy_template
-    image:
-        python:3.8
+#deploy/cp38-cp38-manylinux2010:
+#    <<: 
+#        - *deploy_template
+#    image:
+#        python:3.8
 
 
 # ---------------
@@ -380,17 +412,17 @@ test_minimal/cp37-cp37m-manylinux2010:
     image:
         python:3.7
 
-gpgsign/cp37-cp37m-manylinux2010:
-    <<: 
-        - *gpgsign_template
-    image:
-        python:3.7
+#gpgsign/cp37-cp37m-manylinux2010:
+#    <<: 
+#        - *gpgsign_template
+#    image:
+#        python:3.7
 
-deploy/cp37-cp37m-manylinux2010:
-    <<: 
-        - *deploy_template
-    image:
-        python:3.7
+#deploy/cp37-cp37m-manylinux2010:
+#    <<: 
+#        - *deploy_template
+#    image:
+#        python:3.7
 
 
 # ---------------
@@ -414,17 +446,17 @@ test_minimal/cp36-cp36m-manylinux2010:
     image:
         python:3.6
 
-gpgsign/cp36-cp36m-manylinux2010:
-    <<: 
-        - *gpgsign_template
-    image:
-        python:3.6
+#gpgsign/cp36-cp36m-manylinux2010:
+#    <<: 
+#        - *gpgsign_template
+#    image:
+#        python:3.6
 
-deploy/cp36-cp36m-manylinux2010:
-    <<: 
-        - *deploy_template
-    image:
-        python:3.6
+#deploy/cp36-cp36m-manylinux2010:
+#    <<: 
+#        - *deploy_template
+#    image:
+#        python:3.6
 
 
 # ---------------
